---

 - name: Creating Kong Postgress Volume
   am_docker_volume:
     name: kong-postgres-db
     driver: local
     state: present

 - name: Run Postgress Kong Container
   am_docker_container:
     name: kong-database
     image: postgres:9.4
     hostname: kong-database
     restart: yes
     recreate: yes
     restart_policy: always
     keep_volumes: no
     ports:
       - "5432:5432"
     networks:
       - name: kong-auto-network
     env:
       POSTGRES_USER: kong
       POSTGRES_DB: kong
     volumes:
       - "kong-postgres-db:/var/lib/postgresql/data"
     state: started

 - pause:
    seconds: 15

 - name: Run Kong Container
   am_docker_container:
     name: kong
     image: kong:0.9.9
     hostname: kong
     restart: yes
     restart_policy: always
     recreate: yes
     ports:
       - "8000:8000"
       - "8443:8443"
       - "8001:8001"
       - "7946:7946"
       - "7946:7946/udp"
     links:
       - kong-database
     networks:
       - name: kong-auto-network
     env:
       KONG_DATABASE: postgres
       KONG_PG_HOST: kong-database
     state: started

 - pause:
    seconds: 15

 - name: Run Kong Dashboard Container
   am_docker_container:
     name: kong-dashboard
     image: pgbi/kong-dashboard:v1.3.1
     hostname: kong-dashboard
     restart: yes
     restart_policy: always
     ports:
       - "8080:8080"
     networks:
       - name: kong-auto-network
     state: started

...
